Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -27,7 +27,8 @@ jobs:
       run: npm ci
 
     - name: Run tests
-      run: npm test || echo "::set-output name=tests_failed::true"
+      run: |
+        npm test || echo "tests_failed=true" >> $GITHUB_ENV
 
     - name: Run ESLint
       run: npx eslint .
@@ -39,6 +40,7 @@ jobs:
 
     steps:
     - name: Check if all tests passed
-      run: exit ${{ steps.build.outputs.tests_failed == 'true' }}
-
-    - id: check_status
+      run: |
+        if [ "${{ env.tests_failed }}" == "true" ]; then
+          exit 1
+        fi
