Update node.js.yml
Add name for each step

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -8,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -16,13 +15,22 @@ jobs:
         node-version: [18.x, 20.x, 22.x]
 
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-node@v3
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
-    - run: npm ci
-    - run: npm test || echo "::set-output name=tests_failed::true"
-    - run: npx eslint .
+
+    - name: Install dependencies
+      run: npm ci
+
+    - name: Run tests
+      run: npm test || echo "::set-output name=tests_failed::true"
+
+    - name: Run ESLint
+      run: npx eslint .
 
   check-status:
       runs-on: ubuntu-latest
@@ -31,5 +39,5 @@ jobs:
 
       steps:
       - name: Check if all tests passed
-      - run: exit ${{ steps.build.outputs.tests_failed == 'true' }}
+        run: exit ${{ steps.build.outputs.tests_failed == 'true' }}
       - id: check_status
